apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmjsniper-api
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: 2
  {{- end }}
  selector:
    matchLabels:
      app: kmjsniper-api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: kmjsniper-api
    spec:
      containers:
        - name: kmjsniper-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: env-vars
          ports:
            - name: http
              containerPort: 6969
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
